version: "3.0"
services:
  backend:
    build: ./backend
    image: flask-app
    expose:
      - "5000"
    volumes:
      - /greengrass/v2:/greengrass/v2
    environment:
      - AWS_REGION
      - SVCUID
      - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT
      - AWS_CONTAINER_AUTHORIZATION_TOKEN
      - AWS_CONTAINER_CREDENTIALS_FULL_URI
      - AWS_IOT_THING_NAME
  frontend:
    build: ./frontend
    image: react-webapp
    ports:
      - "3000:3001"
    volumes:
      - /greengrass/v2:/greengrass/v2